export interface Env { DB: D1Database; ENVIRONMENT: string; GROQ_API_KEY?: string; ARTIFACTS?: R2Bucket; AGENT_SESSIONS?: DurableObjectNamespace; }
type ChatMessage = { role: "system" | "user" | "assistant" | "tool"; content: string; tool_call_id?: string };
const allowedOrigin = (request: Request) => request.headers.get("Origin") || "*";
const responseHeaders = (request: Request) => ({ "content-type": "application/json; charset=utf-8", "access-control-allow-origin": allowedOrigin(request), "access-control-allow-methods": "GET,POST,DELETE,OPTIONS", "access-control-allow-headers": "content-type,authorization", "vary": "Origin" });
const json = (request: Request, body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: responseHeaders(request) });
const id = () => crypto.randomUUID();
const safePath = (value: unknown) => typeof value === "string" && value.length > 0 && value.length < 240 && !value.startsWith("/") && !value.split("/").includes("..") && !/[\\\0]/.test(value);
const tools = [{ type: "function", function: { name: "list_files", description: "List files in the current workspace", parameters: { type: "object", properties: { prefix: { type: "string" } } } } }, { type: "function", function: { name: "read_file", description: "Read a file before changing it", parameters: { type: "object", properties: { path: { type: "string" } }, required: ["path"] } } }, { type: "function", function: { name: "write_file", description: "Create or replace a file; ask before destructive changes", parameters: { type: "object", properties: { path: { type: "string" }, content: { type: "string" } }, required: ["path", "content"] } } }, { type: "function", function: { name: "delete_file", description: "Delete a file only when the user explicitly requests it", parameters: { type: "object", properties: { path: { type: "string" } }, required: ["path"] } } }];

export default { async fetch(request: Request, env: Env): Promise<Response> {
  if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: responseHeaders(request) });
  const url = new URL(request.url);
  try {
    if (url.pathname === "/api/health") return json(request, { ok: true, provider: "groq", model: "llama-3.3-70b-versatile", environment: env.ENVIRONMENT, storage: { d1: !!env.DB, r2: !!env.ARTIFACTS } });
    if (url.pathname === "/api/projects" && request.method === "GET") { const result = await env.DB.prepare("SELECT id, name, repository, updated_at FROM projects ORDER BY updated_at DESC LIMIT 50").all(); return json(request, result.results); }
    if (url.pathname === "/api/projects" && request.method === "POST") { const body = await request.json() as { name?: unknown; ownerId?: unknown; repository?: unknown }; if (typeof body.name !== "string" || body.name.length < 1 || body.name.length > 80) return json(request, { error: "Project name must be between 1 and 80 characters" }, 400); const projectId = id(); await env.DB.prepare("INSERT INTO projects (id, owner_id, name, repository) VALUES (?, ?, ?, ?)").bind(projectId, typeof body.ownerId === "string" ? body.ownerId : "local", body.name.trim(), typeof body.repository === "string" ? body.repository : null).run(); return json(request, { id: projectId, name: body.name.trim() }, 201); }
    if (url.pathname === "/api/agent" && request.method === "POST") { if (!env.GROQ_API_KEY) return json(request, { error: "Groq is not configured. Add GROQ_API_KEY as a Worker secret." }, 503); const body = await request.json() as { messages?: ChatMessage[]; workspace?: Record<string, string>; projectId?: string }; if (!Array.isArray(body.messages) || body.messages.length > 40) return json(request, { error: "Invalid conversation" }, 400); const workspace = body.workspace && typeof body.workspace === "object" ? body.workspace : {}; const system = `You are Forge, a senior autonomous coding agent. Inspect before editing, preserve existing architecture, explain changes, and never delete files without explicit confirmation. You can use tools to reason about this workspace. Current files: ${Object.keys(workspace).join(", ") || "none"}.`; const upstream = await fetch("https://api.groq.com/openai/v1/chat/completions", { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${env.GROQ_API_KEY}` }, body: JSON.stringify({ model: "llama-3.3-70b-versatile", temperature: 0.15, stream: false, messages: [{ role: "system", content: system }, ...body.messages], tools, tool_choice: "auto" }) }); const result = await upstream.json(); if (!upstream.ok) return json(request, { error: upstream.status === 429 ? "Groq is rate limited. Try again shortly." : "Groq request failed", status: upstream.status }, upstream.status >= 500 ? 502 : upstream.status); const message = (result as { choices?: Array<{ message?: ChatMessage }> }).choices?.[0]?.message; if (!message) return json(request, { error: "Groq returned no assistant message" }, 502); if (body.projectId) await env.DB.prepare("INSERT INTO messages (id, conversation_id, role, content) SELECT ?, id, ?, ? FROM conversations WHERE project_id = ? ORDER BY updated_at DESC LIMIT 1").bind(id(), "assistant", message.content || "", body.projectId).run(); return json(request, { provider: "groq", model: "llama-3.3-70b-versatile", message }); }
    return json(request, { error: "Not found" }, 404);
  } catch (error) { console.error("[forge-worker] request failed", error); return json(request, { error: "The request could not be completed safely" }, 500); }
} }; 
